# Generated by Django 5.2.1 on 2025-05-10 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_post_likes_post_total_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='total_likes',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_images/'),
        ),
    ]
